---
- name: Install python
  ansible.builtin.apt:
    name: python3
    state: latest
- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: latest
- name: copy desktop autostart files
  ansible.builtin.copy:
    src: RpiGlucose.desktop
    dest: /home/vese/.config/autostart/RpiGlucose.desktop
    force: true
- name: copy app files
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../app"
    dest: /home/vese
    force: true
  tags: install_app
- name: Ensure correct permissions for logs directory
  ansible.builtin.file:
    path: /home/vese/app/logs
    state: directory
    mode: '0755'
    owner: vese
    group: vese
  tags: install_app
- name: Ensure correct permissions for output.log file
  ansible.builtin.file:
    path: /home/vese/app/logs/output.log
    state: touch
    mode: '0644'
    owner: vese
    group: vese
  tags: install_app
- name: Install requirements
  ansible.builtin.pip:
    requirements: /home/vese/app/requirements.txt
    executable: /usr/bin/pip3